// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnf5va-fNckU3_GyAzi0TNkyKS1nIT59Q',
    appId: '1:426988229556:web:14f15cbe32df726eef98e1',
    messagingSenderId: '426988229556',
    projectId: 'e-commerce-adinan',
    authDomain: 'e-commerce-adinan.firebaseapp.com',
    storageBucket: 'e-commerce-adinan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM4rQu0J41xplIW48uR2-59m_fPdHVZIQ',
    appId: '1:426988229556:android:47001b1536dadafcef98e1',
    messagingSenderId: '426988229556',
    projectId: 'e-commerce-adinan',
    storageBucket: 'e-commerce-adinan.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnf5va-fNckU3_GyAzi0TNkyKS1nIT59Q',
    appId: '1:426988229556:web:0b1ef8a29cb0c756ef98e1',
    messagingSenderId: '426988229556',
    projectId: 'e-commerce-adinan',
    authDomain: 'e-commerce-adinan.firebaseapp.com',
    storageBucket: 'e-commerce-adinan.firebasestorage.app',
  );
}
